# Generated by Django 2.2.24 on 2025-05-26 00:36

from django.db import migrations

def fill_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year is None:
            continue
        flat.new_building = flat.construction_year >= 2015
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20250526_0252'),
    ]

    operations = [
        migrations.RunPython(fill_new_building),
    ]
