# Generated by Django 2.2.24 on 2025-05-27 00:07

from django.db import migrations
import phonenumbers


def to_normalize_phones(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        raw_phone = flat.owners_phonenumber
        try:
            phone = phonenumbers.parse(raw_phone, 'RU')
            if phonenumbers.is_valid_number(phone):
                flat.owner_pure_phone = phonenumbers.format_number(
                    phone,
                    phonenumbers.PhoneNumberFormat.E164
                )
                flat.save(update_fields=['owner_pure_phone'])
        except phonenumbers.NumberParseException:
            print(f'Не удалось распарсить: {raw_phone}')
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(to_normalize_phones),
    ]
