# Generated by Django 2.2.24 on 2025-05-27 00:59

from django.db import migrations


def link_owners_to_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            name=flat.owner_deprecated,
            phonenumber=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone
        )
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20250527_0358'),
    ]

    operations = [
        migrations.RunPython(link_owners_to_flats, reverse_code=migrations.RunPython.noop),
    ]
